### ISSUE TITLE
Third party script support

### ISSUE THREAD

**Issue by edgarlr** [Sprokets/nextjs-csp-report-only#2]
The example works great for all the autogenerated scripts but doesn't seems to be working with third-party scripts.

Steps to reproduce.

1. Create a new file or embed a Script component with external `src` and pass the nonce to the script from the headers. e.g. 
```js

// components/external-script.tsx

const ExternalScript = () => {
 const nonce = headers().get('x-nonce')

  return (
    <Script
      nonce={nonce ?? undefined}
      src='https://example.com/script.js'
    />
  )
 }
```

**Comment by danieltott** [comment]
Hey @edgarlr !

This approach should work fine - you can see it working here:

https://nextjs-csp-report-only.vercel.app/

Code:

https://github.com/Sprokets/nextjs-csp-report-only/blob/2372bcdee30b4f7415ab2fbf5c398ead3931f47b/app/ExternalScript.tsx#L1-L15

https://github.com/Sprokets/nextjs-csp-report-only/blob/2372bcdee30b4f7415ab2fbf5c398ead3931f47b/app/layout.tsx#L20

I would make sure your `nonce` value is coming through - in your middleware you need to make sure you're setting `x-nonce` on the _request_ headers so that your pages can read them:

https://github.com/Sprokets/nextjs-csp-report-only/blob/3abe89ff6672c2513003e08960aacf49fe03cc2b/middleware.ts#L43-L76
